id: PC4B11D58
initial_creation_type: ocr
source_metadata:
  volumes:
    a4ec317489f544488f96ee9df2030160:
      base_file: v056.txt
      image_group_id: I1PD95901
      title: ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པའི་སྙིང་པོ་ཞེས་བྱ་བའི་འགྲེལ་པ།
      total_pages: 1682
      volume_number: 56
